import "package:json_annotation/json_annotation.dart";
part 'user.g.dart';

@JsonSerializable()
class JwtToken {
  JwtToken(this.token);

  String token;

  factory JwtToken.fromJson(Map<String, dynamic> json) =>
      _$JwtTokenFromJson(json);

  Map<String, dynamic> toJson() => _$JwtTokenToJson(this);
}

@JsonSerializable()
class Account {
  String id;
  String createdAt;
  String updatedAt;
  String userId;
  Settings settings;
  String firstName;
  String lastName;
  String name;
  String initials;
  String avatarObjectKey;
  String avatarUrl;
  String backgroundObjectKey;
  String backgroundUrl;
  String locale;
  String timezoneOffset;
  bool daylightSavings;
  String phoneNumber;
  User user;
  String profile;
  String jobTitle;
  String location;
  String bio;
  String webUri1;
  String webUri2;

  Account();
}

@JsonSerializable()
class Settings {
  String id;
  String accountId;
  String notificationSound;
  bool sendDailyEmail;
  int pushRepeatInterval;
  String doNotDisturbUntil;
  String defaultNetworkId;

  Settings();
}

@JsonSerializable()
class User {
  String id;
  String username;
  bool isStaff;
  String lastLogin;
  bool lockedOut;
  String email;
  String accountId;

  User();
}

// Generated by https://quicktype.io

@JsonSerializable()
class NetworkAccount {
  String id;
  String name;
  String avatarUrl;
  Settings settings;
  SubscriberAccount subscriberAccount;
  List<String> geofences;
  String parentId;

  NetworkAccount();
}

@JsonSerializable()
class NetworkSettings {
  bool directoryEnabled;
  bool shiftsEnabled;
  bool formsEnabled;
  String formsFolderId;
  bool teamsEnabled;
  int teamMembershipLimit;
  bool devicePasscodeRequired;
  bool passportEnabled;
  bool passportLocationTrackingEnabled;
  List<AccountProfileField> accountProfileFields;

  NetworkSettings();
}

@JsonSerializable()
class AccountProfileField {
  String name;
  bool accountProfileFieldDefault;
  String listId;
  bool readOnly;
  String emoji;

  AccountProfileField();
}

@JsonSerializable()
class SubscriberAccount {
  String id;
  bool isNetworkNotifier;
  bool isShiftsGroupMember;
  bool isShiftsApprover;

  SubscriberAccount();
}
