import "package:built_collection/built_collection.dart";
import "package:built_value/built_value.dart";
import "package:json_annotation/json_annotation.dart";
part 'user.g.dart';

abstract class JwtToken implements Built<JwtToken, JwtTokenBuilder> {
  String get token;
  JwtToken._();

  factory JwtToken([void Function(JwtTokenBuilder) updates]) = _$JwtToken;
}

// Generated by https://quicktype.io

abstract class Account implements Built<Account, AccountBuilder> {
  String get id;
  String get createdAt;
  String get updatedAt;
  String get userId;
  Settings get settings;
  String get firstName;
  String get lastName;
  String get name;
  String get initials;
  String get avatarObjectKey;
  String get avatarUrl;
  String get backgroundObjectKey;
  String get backgroundUrl;
  String get locale;
  String get timezoneOffset;
  bool get daylightSavings;
  String get phoneNumber;
  User get user;
  String get profile;
  String get jobTitle;
  String get location;
  String get bio;
  String get webUri1;
  String get webUri2;

  Account._();
  factory Account([void Function(AccountBuilder) updates]) = _$Account;
}

abstract class Settings implements Built<Settings, SettingsBuilder> {
  String get id;
  String get accountId;
  String get notificationSound;
  bool get sendDailyEmail;
  int get pushRepeatInterval;
  String get doNotDisturbUntil;
  String get defaultNetworkId;

  Settings._();
  factory Settings([void Function(SettingsBuilder) updates]) = _$Settings;
}

abstract class User implements Built<User, UserBuilder> {
  String get id;
  String get username;
  bool get isStaff;
  String get lastLogin;
  bool get lockedOut;
  String get email;
  String get accountId;

  User._();
  factory User([void Function(UserBuilder) updates]) = _$User;
}

// Generated by https://quicktype.io

abstract class NetworkAccount
    implements Built<NetworkAccount, NetworkAccountBuilder> {
  String get id;
  String get name;
  String get avatarUrl;
  Settings get settings;
  SubscriberAccount get subscriberAccount;
  List<String> get geofences;
  String get parentId;

  NetworkAccount._();
  factory NetworkAccount([void Function(NetworkAccountBuilder) updates]) =
      _$NetworkAccount;
}

abstract class NetworkSettings
    implements Built<NetworkSettings, NetworkSettingsBuilder> {
  bool get directoryEnabled;
  bool get shiftsEnabled;
  bool get formsEnabled;
  String get formsFolderId;
  bool get teamsEnabled;
  int get teamMembershipLimit;
  bool get devicePasscodeRequired;
  bool get passportEnabled;
  bool get passportLocationTrackingEnabled;
  List<AccountProfileField> get accountProfileFields;

  NetworkSettings._();
  factory NetworkSettings([void Function(NetworkSettingsBuilder) updates]) =
      _$NetworkSettings;
}

abstract class AccountProfileField
    implements Built<AccountProfileField, AccountProfileFieldBuilder> {
  String get name;
  bool get accountProfileFieldDefault;
  String get listId;
  bool get readOnly;
  String get emoji;

  AccountProfileField._();
  factory AccountProfileField(
          [void Function(AccountProfileFieldBuilder) updates]) =
      _$AccountProfileField;
}

abstract class SubscriberAccount
    implements Built<SubscriberAccount, SubscriberAccountBuilder> {
  String get id;
  bool get isNetworkNotifier;
  bool get isShiftsGroupMember;
  bool get isShiftsApprover;

  SubscriberAccount._();
  factory SubscriberAccount([void Function(SubscriberAccountBuilder) updates]) =
      _$SubscriberAccount;
}
